### ISSUE TITLE
Trying to install napari (-e .[dev])

### ISSUE THREAD

**Issue by psobolewskiPhD** [tlambert03/pamba#3]
* pamba version: 0.1.dev11+g0e5905e
* Python version: 3.10.6
* Operating System: macOS 12.5.1 (arm64)

### Description

Trying to use `pamba` to install editable napari dev env using `pamba install -e .[dev]`

### What I Did

Made a fresh 3.10 env. Installed pamba.
Then cd into napari folder.
`pamba install -e .[dev]`
conda deps were installed correctly (can see them with `conda list`), but the pip part fails
```
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
installing remaining pip deps
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/bin/pamba", line 8, in <module>
    sys.exit(main())
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/lib/python3.10/site-packages/pamba/cli.py", line 202, in main
    parse_args()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/lib/python3.10/site-packages/pamba/cli.py", line 196, in parse_args
    args.func(args, conda_args)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/lib/python3.10/site-packages/pamba/cli.py", line 178, in install
    pip_install([r.replace(" ", "") for r in from_pip])
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/lib/python3.10/site-packages/pamba/cli.py", line 144, in pip_install
    check_call(["pip", "install"] + extra_args + requires)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'install', 'tensorstore>=0.1.13']' died with <Signals.SIGKILL: 9>.
```
I manually pip installed tensorstore which has 3.10 arm64 wheels, so it worked fine, and re-ran `pamba install -e .[dev]` and everything worked.
🤔 

Edit: in a fresh 3.10 env, doing `pamba install -e .` also errors:
```
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
installing /Users/piotrsobolewski/Dev/napari in editable mode
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari2/bin/pamba", line 8, in <module>
    sys.exit(main())
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari2/lib/python3.10/site-packages/pamba/cli.py", line 202, in main
    parse_args()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari2/lib/python3.10/site-packages/pamba/cli.py", line 196, in parse_args
    args.func(args, conda_args)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari2/lib/python3.10/site-packages/pamba/cli.py", line 181, in install
    pip_install([str(pth)], ["-e"])
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari2/lib/python3.10/site-packages/pamba/cli.py", line 144, in pip_install
    check_call(["pip", "install"] + extra_args + requires)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari2/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'install', '-e', '/Users/piotrsobolewski/Dev/napari']' died with <Signals.SIGKILL: 9>.
```
BTW, I notice that the conda part installs napari (0.4.14 in fact) even though I'm doing an `-e` install of napari...
And once again, just re-runing `pamba install -e .` works:
```
Successfully built napari
Installing collected packages: napari
  Attempting uninstall: napari
    Found existing installation: napari 0.4.14
    Uninstalling napari-0.4.14:
      Successfully uninstalled napari-0.4.14
Successfully installed napari-0.4.17rc4.dev11+g4103d7e5
```

**Comment by tlambert03** [comment]
thanks @psobolewskiPhD ... yeah I've seen this too... where just re-running works.

@perlman also saw this: https://napari.zulipchat.com/#narrow/stream/212875-general/topic/Napari.20.26.20Python.20on.20Apple.20M1/near/285054566

I tried to dig into it, but not immediately sure what's causing it.  The actual call to pip install is rather simple:

https://github.com/tlambert03/pamba/blob/0e5905e262db8c8b2addf21a485fd449c3bb5690/src/pamba/cli.py#L178

https://github.com/tlambert03/pamba/blob/0e5905e262db8c8b2addf21a485fd449c3bb5690/src/pamba/cli.py#L141-L144

so there appears to be something magically bad about calling that subprocess immediately after having called the conda installer, where the conda installer _did_ install something?  perhaps I should just change it from `check_call` to something less strict?

**Comment by psobolewskiPhD** [comment]
Yeah, it works if the conda fires separately...
Maybe there needs to be a pause or something before doing the pip?

**Comment by tlambert03** [comment]
> Maybe there needs to be a pause or something before doing the pip?

yeah, that seems reasonable.  but [check_call](https://docs.python.org/3/library/subprocess.html#subprocess.check_call) _should_ have waited for the previous (conda) process to entirely complete... so it's hard to imagine what we'd be pausing for?
